# Generated by Django 4.2.28 on 2026-02-17 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='created_at',
        ),
    ]
