# Generated by Django 4.2.28 on 2026-02-17 10:32

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_alter_order_options_alter_orderitem_options_and_more'),
        ('payments', '0002_remove_payment_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-paid_at'], 'verbose_name': "To'lov", 'verbose_name_plural': "To'lovlar"},
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Miqdori'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='debt_note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Qarz izohi'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='is_debt',
            field=models.BooleanField(default=False, verbose_name='Qarzmi'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Naqd pul'), ('CARD', 'Karta'), ('QR', 'QR kod')], max_length=10, verbose_name="To'lov usuli"),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='Buyurtma'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name="To'langan vaqt"),
        ),
        migrations.AlterField(
            model_name='payment',
            name='received_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_received', to=settings.AUTH_USER_MODEL, verbose_name='Qabul qiluvchi'),
        ),
    ]
