# Generated by Django 4.2.28 on 2026-02-17 10:32

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0002_expensecategory_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-spent_at'], 'verbose_name': 'Xarajat', 'verbose_name_plural': 'Xarajatlar'},
        ),
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'verbose_name': 'Xarajat kategoriyasi', 'verbose_name_plural': 'Xarajat kategoriyalari'},
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Miqdori'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.expensecategory', verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='comment',
            field=models.CharField(blank=True, max_length=255, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses_created', to=settings.AUTH_USER_MODEL, verbose_name='Kim tomonidan'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='spent_at',
            field=models.DateTimeField(verbose_name='Xarajat sanasi'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faolmi'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='name',
            field=models.CharField(max_length=80, unique=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan'),
        ),
    ]
