# Generated by Django 4.2.28 on 2026-02-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MANAGER', 'Menejer'), ('WAITER', 'Ofitsiant'), ('CHEF', 'Oshpaz')], default='WAITER', max_length=20, verbose_name='Rol'),
        ),
    ]
