# Generated by Django 4.2.28 on 2026-02-17 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Buyurtma', 'verbose_name_plural': 'Buyurtmalar'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['id'], 'verbose_name': 'Buyurtma elementi', 'verbose_name_plural': 'Buyurtma elementlari'},
        ),
        migrations.AlterModelOptions(
            name='orderstatuslog',
            options={'ordering': ['-changed_at'], 'verbose_name': "Status o'zgarishi", 'verbose_name_plural': "Status o'zgarishlari"},
        ),
    ]
